# Generated by Django 4.2.17 on 2024-12-04 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cronograma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('documento', models.CharField(max_length=50)),
                ('curso', models.CharField(max_length=15)),
                ('edad', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('mes', models.IntegerField()),
                ('meses', models.CharField(max_length=3)),
                ('valor', models.IntegerField()),
                ('fecha_evento', models.DateField(blank=True, null=True)),
                ('intereses', models.IntegerField()),
                ('cronograma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manejador_cronogramas.cronograma')),
            ],
        ),
        migrations.AddField(
            model_name='cronograma',
            name='estudiante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manejador_cronogramas.estudiante'),
        ),
    ]
