# Generated by Django 4.2.17 on 2024-12-04 21:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manejador_cronogramas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cronograma',
            name='estudiante',
        ),
        migrations.AddField(
            model_name='estudiante',
            name='cronograma',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='manejador_cronogramas.cronograma'),
        ),
    ]
