# Generated by Django 4.2.17 on 2024-12-04 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manejador_cronogramas', '0003_remove_pago_nombre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estudiante',
            name='cronograma',
        ),
        migrations.AddField(
            model_name='estudiante',
            name='cronogramas',
            field=models.ManyToManyField(related_name='estudiantes', to='manejador_cronogramas.cronograma'),
        ),
        migrations.AddField(
            model_name='pago',
            name='nombre',
            field=models.CharField(default='Pago sin nombre', max_length=50),
        ),
    ]
