# Generated by Django 4.2.17 on 2024-12-04 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manejador_cronogramas', '0005_remove_pago_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='nombre',
            field=models.CharField(default='Pago sin nombre', max_length=50),
        ),
    ]
