# Generated by Django 4.2.17 on 2024-12-04 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manejador_cronogramas', '0006_pago_nombre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pago',
            name='nombre',
        ),
    ]
