# Generated by Django 4.2.17 on 2024-12-04 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manejador_cronogramas', '0007_remove_pago_nombre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estudiante',
            name='cronogramas',
        ),
        migrations.AddField(
            model_name='cronograma',
            name='estudiantes',
            field=models.ManyToManyField(related_name='cronogramas', to='manejador_cronogramas.estudiante'),
        ),
    ]
